name: "mageck_count"
description: mageck count for functional genomics, reads are usually mapped to a specific sgRNA
keywords:
  - sort
  - functional genomics
  - sgRNA
  - CRISPR-Cas9
tools:
  - "mageck":
      description: "MAGeCK (Model-based Analysis of Genome-wide CRISPR-Cas9 Knockout), an algorithm to process, QC, analyze and visualize CRISPR screening data."
      homepage: "https://sourceforge.net/p/mageck/wiki/Home/"
      documentation: "https://sourceforge.net/p/mageck/wiki/demo/#step-4-run-the-mageck-count-command"
      tool_dev_url: "None"
      doi: ""
      licence: "['BSD License']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - library:
      type: file
      description: library file containing the sgRNA and gene name
      pattern: "*.{csv,txt,tsv}"
  - reads:
      type: files
      description: library file containing the sgRNA and gene name
      pattern: "*.{fq,fastq,fastq.gz,fq.gz}"
  - name:
      type: string
      description: name of the output data

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - norm:
      type: file
      description: File containing normalized read counts
      pattern: "*.count_normalized.txt"
  - count:
      type: file
      description: File containing read counts
      pattern: "*.countsummary.txt"

authors:
  - "@LaurenceKuhl"
